config/routes.rb
Rails.application.routes.draw do
  resources :favoritos
  resources :tarefas
  get 'lista/index'
  root 'lista#index'
  resources :lista
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  belongs_to :listum
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:listum_id, :texto, :aberta)
    end
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/tarefas/_form.html.erb
<%= form_for(tarefa) do |f| %>
  <% if tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% tarefa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listum_id %>
    <%= f.text_field :listum_id %>
  </div>

  <div class="field">
    <%= f.label :texto %>
    <%= f.text_field :texto %>
  </div>

  <div class="field">
    <%= f.label :aberta %>
    <%= f.check_box :aberta %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editing Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tarefas</h1>

<table>
  <thead>
    <tr>
      <th>Listum</th>
      <th>Texto</th>
      <th>Aberta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tarefas.each do |tarefa| %>
      <tr>
        <td><%= tarefa.listum %></td>
        <td><%= tarefa.texto %></td>
        <td><%= tarefa.aberta %></td>
        <td><%= link_to 'Show', tarefa %></td>
        <td><%= link_to 'Edit', edit_tarefa_path(tarefa) %></td>
        <td><%= link_to 'Destroy', tarefa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<h1>New Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listum:</strong>
  <%= @tarefa.listum %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @tarefa.texto %>
</p>

<p>
  <strong>Aberta:</strong>
  <%= @tarefa.aberta %>
</p>

<%= link_to 'Edit', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Back', tarefas_path %>