config/routes.rb
Rails.application.routes.draw do
  resources :favoritos
  resources :tarefas
  get 'lista/index'
  root 'lista#index'
  resources :lista
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/lista_controller.rb
class ListaController < ApplicationController
  before_action :set_listum, only: [:show, :edit, :update, :destroy]

  # GET /lista
  # GET /lista.json
  def index
    @lista = Listum.all
  end

  # GET /lista/1
  # GET /lista/1.json
  def show
  end

  # GET /lista/new
  def new
    @listum = Listum.new
  end

  # GET /lista/1/edit
  def edit
  end

  # POST /lista
  # POST /lista.json
  def create
    @listum = Listum.new(listum_params)

    respond_to do |format|
      if @listum.save
        format.html { redirect_to @listum, notice: 'Listum was successfully created.' }
        format.json { render :show, status: :created, location: @listum }
      else
        format.html { render :new }
        format.json { render json: @listum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lista/1
  # PATCH/PUT /lista/1.json
  def update
    respond_to do |format|
      if @listum.update(listum_params)
        format.html { redirect_to @listum, notice: 'Listum was successfully updated.' }
        format.json { render :show, status: :ok, location: @listum }
      else
        format.html { render :edit }
        format.json { render json: @listum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lista/1
  # DELETE /lista/1.json
  def destroy
    @listum.destroy
    respond_to do |format|
      format.html { redirect_to lista_url, notice: 'Listum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listum
      @listum = Listum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listum_params
      params.require(:listum).permit(:user_id, :privada)
    end
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/views/lista/_form.html.erb
<%= form_for(listum) do |f| %>
  <% if listum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listum.errors.count, "error") %> prohibited this listum from being saved:</h2>

      <ul>
      <% listum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id  %>
  </div>

  <div class="field">
    <%= f.label :privada %>
    <%= f.check_box :privada %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lista/edit.html.erb
<h1>Editing Listum</h1>

<%= render 'form', listum: @listum %>

<%= link_to 'Show', @listum %> |
<%= link_to 'Back', lista_path %>

app/views/lista/index.html.erb
<h1>Lista</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Privada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lista.each do |listum| %>
      <tr>
        <td><%= listum.user.username %></td>
        <td><%= listum.privada %></td>
        <td><%= link_to 'Show', listum %></td>
        <td><%= link_to 'Edit', edit_listum_path(listum) %></td>
        <td><%= link_to 'Destroy', listum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listum', new_listum_path %>
<br>

app/views/lista/new.html.erb
<h1>New Listum</h1>

<%= render 'form', listum: @listum %>

<%= link_to 'Back', lista_path %>

app/views/lista/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @listum.user.id %>
</p>

<p>
  <strong>Privada:</strong>
  <%= @listum.privada %>
</p>

<%= link_to 'Edit', edit_listum_path(@listum) %> |
<%= link_to 'Back', lista_path %>