config/routes.rb
Rails.application.routes.draw do
  resources :favoritos
  resources :tarefas
  get 'lista/index'
  root 'lista#index'
  resources :lista
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorito.rb
class Favorito < ApplicationRecord
  belongs_to :lista
  belongs_to :user
end

app/controllers/favoritos_controller.rb
class FavoritosController < ApplicationController
  before_action :set_favorito, only: [:show, :edit, :update, :destroy]

  # GET /favoritos
  # GET /favoritos.json
  def index
    @favoritos = Favorito.all
  end

  # GET /favoritos/1
  # GET /favoritos/1.json
  def show
  end

  # GET /favoritos/new
  def new
    @favorito = Favorito.new
  end

  # GET /favoritos/1/edit
  def edit
  end

  # POST /favoritos
  # POST /favoritos.json
  def create
    @favorito = Favorito.new(favorito_params)

    respond_to do |format|
      if @favorito.save
        format.html { redirect_to @favorito, notice: 'Favorito was successfully created.' }
        format.json { render :show, status: :created, location: @favorito }
      else
        format.html { render :new }
        format.json { render json: @favorito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favoritos/1
  # PATCH/PUT /favoritos/1.json
  def update
    respond_to do |format|
      if @favorito.update(favorito_params)
        format.html { redirect_to @favorito, notice: 'Favorito was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorito }
      else
        format.html { render :edit }
        format.json { render json: @favorito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favoritos/1
  # DELETE /favoritos/1.json
  def destroy
    @favorito.destroy
    respond_to do |format|
      format.html { redirect_to favoritos_url, notice: 'Favorito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorito
      @favorito = Favorito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorito_params
      params.require(:favorito).permit(:lista_id, :user_id, :followed)
    end
end

app/helpers/favoritos_helper.rb
module FavoritosHelper
end

app/views/favoritos/_form.html.erb
<%= form_for(favorito) do |f| %>
  <% if favorito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorito.errors.count, "error") %> prohibited this favorito from being saved:</h2>

      <ul>
      <% favorito.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lista_id %>
    <%= f.text_field :lista_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :followed %>
    <%= f.number_field :followed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favoritos/edit.html.erb
<h1>Editing Favorito</h1>

<%= render 'form', favorito: @favorito %>

<%= link_to 'Show', @favorito %> |
<%= link_to 'Back', favoritos_path %>

app/views/favoritos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favoritos</h1>

<table>
  <thead>
    <tr>
      <th>Lista</th>
      <th>User</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favoritos.each do |favorito| %>
      <tr>
        <td><%= favorito.lista %></td>
        <td><%= favorito.user %></td>
        <td><%= favorito.followed %></td>
        <td><%= link_to 'Show', favorito %></td>
        <td><%= link_to 'Edit', edit_favorito_path(favorito) %></td>
        <td><%= link_to 'Destroy', favorito, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorito', new_favorito_path %>

app/views/favoritos/new.html.erb
<h1>New Favorito</h1>

<%= render 'form', favorito: @favorito %>

<%= link_to 'Back', favoritos_path %>

app/views/favoritos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lista:</strong>
  <%= @favorito.lista %>
</p>

<p>
  <strong>User:</strong>
  <%= @favorito.user %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @favorito.followed %>
</p>

<%= link_to 'Edit', edit_favorito_path(@favorito) %> |
<%= link_to 'Back', favoritos_path %>